---
galaxy_info:
  author: boxp
  description: Kubernetes cluster upgrade automation for Orange Pi Zero 3 control plane nodes
  company: Personal
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
    - name: Debian
      versions:
        - bullseye
        - bookworm
  galaxy_tags:
    - kubernetes
    - upgrade
    - kubeadm
    - etcd
    - controlplane

dependencies: []
