galaxy_info:
  role_name: babashka
  namespace: arch
  author: boxp
  description: Install Babashka (bb) Clojure scripting tool
  company: boxp.io

  license: MIT

  min_ansible_version: "2.9"

  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble

  galaxy_tags:
    - tools
    - clojure
    - scripting

dependencies: []
