---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: control-plane-test
    image: "geerlingguy/docker-ubuntu2404-ansible:latest"
    platform: "${MOLECULE_DOCKER_PLATFORM:-linux/amd64}"
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    command: /lib/systemd/systemd
    env:
      DEBIAN_FRONTEND: noninteractive
    groups:
      - control_plane
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
    prepare: prepare.yml
  inventory:
    group_vars:
      all:
        kubernetes_upgrade_version: "1.35.1"
        kubernetes_upgrade_package: "1.35.1-1.1"
        crio_upgrade_version: "1.35.0"
        node_role: "control_plane"
        is_first_control_plane: true
    host_vars:
      control-plane-test:
        ansible_python_interpreter: /usr/bin/python3
        hardware_type: orange_pi_zero3
        architecture: arm64
verifier:
  name: ansible
